### ISSUE TITLE
comparision

### ISSUE THREAD

**Issue by acampanelli-altran** [3imed-jaberi/p-crypt#9]
hello, thanks for your support....
I have a problem... if I try to compare hash string (saved on my DB) and clear string crypted the comparison return False...  it's strange or not?

**Comment by 3imed-jaberi** [comment]
@acampanelli-altran, welcome 👋🏻, sorry for the delay.
There's no problem because the hash string change every time you make the call. 

```js
const Password = 'Imed Jaberi', Secret = 'SomeSecret';
// same secret, same password, but we have different hash .. 
const firstHash = await Crypt(Secret, Password);
const secondHash = await Crypt(Secret, Password);
firstHash === secondHash // false
```
The only way to compare is by using the Compare function with the same Secret.

```js
const Password = 'Imed Jaberi', Secret = 'SomeSecret';
// same secret, same password, but we have different hash .. 
const passwordHashed = await Crypt(Secret, Password);
const isValidPassword = await Compare(Secret, Password, HashedPassword);
isValidPassword // ture
```
